### ISSUE TITLE
question - pressure vs duration

### ISSUE THREAD

**Issue by knoxcard** [stuyam/pressure#78]
Is this really measuring pressure? or is it simpy duration?

harder the press = longer the duration

**Comment by stuyam** [comment]
@knoxcard is depends on the device and browser you are using. The hardware and browser both need to support giving force values from the trackpad or screen. I they don't support it then pressure.js falls back to using duration. We refer to the duration settings as the Polyfill since it is fallback support: https://github.com/stuyam/pressure#polyfill-speed-up
